version: '2'

services:
  rabbit:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - rabbit-network

  identity-db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    ports: 
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Pass@word
    networks:
      - identity-network
    
  identity-server:
    build:
      context: ./src/IdentityServer
    ports:
      - "5000:5000"
    networks:
      - identity-network
    depends_on: 
      - identity-db
  
  identity-seeder:
    build:
      context: ./src/IdentityServer
      dockerfile: seed.dockerfile
    networks:
      - identity-network
      - rabbit-network
    depends_on: 
      - identity-db
      - rabbit
      - banking

  gateway:
    build:
      context: ./src/Gateway
    ports:
      - "5002:5002"
    networks:
      - gateway-network
    depends_on: 
      - real-time
      - banking
      
  real-time:
    build:
      context: ./src/RealTime
    ports:
      - "5001:5001"
    networks:
      - gateway-network
      - rabbit-network
    depends_on:
      - rabbit

  banking-db:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - banking-network
  
  banking:
    build:
      context: ./src/banking-server
    ports:
      - "3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      MONGODB_CONNECTION_STRING: "mongodb://root:password@banking-db:27017"
      RABBITMQ_HOST: "rabbit"
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: "guest"
      RABBITMQ_PASSWORD: "guest"
    networks:
      - gateway-network
      - banking-network
      - rabbit-network
    depends_on:
      - rabbit
      - banking-db
  
  admin-client:
    build:
      context: ./src/admin-client
    ports:
      - 4200:80
    environment: 
      base: "http://localhost"
      client: "http://localhost:4200"
    networks:
      - gateway-network

  user-client:
    build:
      context: ./src/user-client
    ports:
      - 4201:80
    environment: 
      base: "http://localhost"
      client: "http://localhost:4201"
    networks: 
      - gateway-network

networks:
  gateway-network: 
    driver: bridge
  identity-network:
    driver: bridge
  banking-network:
    driver: bridge
  rabbit-network:
    driver: bridge