version: '2'

services:
  identity-db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    ports: 
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Pass@word
    networks:
      - identity-network
    
  identity-server:
    build:
      context: ./src/IdentityServer
    ports:
      - "5000:5000"
    networks:
      - identity-network
    depends_on: 
      - identity-db
  
  identity-seeder:
    build:
      context: ./src/IdentityServer
      dockerfile: seed.dockerfile
    networks:
      - identity-network
    depends_on: 
      - identity-db

  gateway:
    build:
      context: ./src/Gateway
    ports:
      - "5002:5002"
    networks:
      - gateway-network

  real-time:
    build:
      context: ./src/RealTime
    ports:
      - "5001"
    networks:
      - gateway-network
  
  banking:
    build:
      context: ./src/banking-server
    ports:
      - "3000"
    networks:
      - gateway-network

  admin-client:
    build:
      context: ./src/admin-client
    ports:
      - 4200:80
    networks:
      - gateway-network

networks:
  gateway-network: 
    driver: bridge
  identity-network:
    driver: bridge